### ISSUE TITLE
Items in browse categories & search results should be sortable by date

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme#1348]
Add date as a sort option for search results and the browse category page. 

<img width="926" alt="Screen Shot 2021-11-08 at 11 46 31 AM" src="https://user-images.githubusercontent.com/37662787/140783433-beec30a7-0da3-4278-a8a6-444441313052.png">

**Comment by ggeisler** [comment]
@jacobthill I know the desire to sort by date came up in the context of the interviewee looking at a browse category, but I'd suggest the application update we might want here is to add Date as a _search results_ sort field. I believe we use the same sort field configuration for all search results, whether displayed on a browse category results page or a normal search results page. 

In other words, I think a user who wants to sort items by date on a browse category results page would be just as likely to want to sort items by date when doing a normal search.

**Comment by jacobthill** [comment]
Thanks @ggeisler, that makes sense to me. I'll update this ticket.

**Comment by jacobthill** [comment]
Some potential challenges with implementing this feature are the limitations of the metadata. Some records will not have normalized dates, though the vast majority do. Others will have wide ranges (e.g. Cambridge records are 6th to 19th century). We will need to choose either the earliest or latest year to sort on. Probably makes sense to choose the earliest year. We will also need to provide some context to users about some of the features and the data quality. We should probably have an about page that gives enough context about how the metadata gets into DLME, some limitations, potentially confusing results from some features, and what to do when encountering errors. Overall, it seems like it will still be useful and could lead to better metadata in the long run.

**Comment by jacobthill** [comment]
@corylown thank you for this very detailed analysis. Its really helpful. 

- I think we do want to use the min function for sorting; ascending order definitely makes more sense than descending order. 
- Records with missing values should always sort at the end. This will maintain consistency with existing sort by functionality for 'creator' etc. and make designing a way to provide user contest in the UI a bit easier.
- I think its fine to create a new field for sorting. Would this need to be done in transform. Ideally we would not need to worry about that e.g. the web application could generate the needed field by taking the first value in `cho_date_range_norm_isim` but if that will require any level of complexity we can do it during transform.
- Yes we can use only the `cho_date_range_norm_isim` or the lowest value (should also be the first value) from it. 

Definitely agree that we need to think about the contextual information we provide to users on the about page. I also wonder if there are things that we can do in the UI on this page to indicate that dates are sorted based on the earliest year and that records missing years will be at the end. @ggeisler I opened a new ticket and added the `design_needed` tag https://github.com/sul-dlss/dlme/issues/1470. In addition to that I will include this in our search tips page revisions.

**Comment by ggeisler** [comment]
@jacobthill I understand the ideas of displaying missing values at the end and using the min date value, but am unclear what the second part of this means:

> I think we do want to use the min function for sorting; ascending order definitely makes more sense than descending order.

Are we only providing the user with a single sort option (`Sort by Date (old to new)`) or are we offering to sort dates in either direction (also providing `Sort by Date (new to old)`)?

**Comment by corylown** [comment]
@jacobthill I think it would be best to start from how we'd prefer date sort to work and the design we'd like and work back to technical implementation concerns and complexity. My assessment at the moment is that any solution is likely to involve some changes to the Solr schema, possibly an additional date field for sort (either defined in the transform step, or possibly, as a copy field directive in the Solr schema), and some configuration/design on the front end. I'd be happy to have a brief meeting about this to talk it through. The options available and trade-offs in complexity are enough to warrant some discussion.

**Comment by ggeisler** [comment]
To be clear, the design in #1470 will work either way (only sort by old to new, or both options). If we only want to offer old to new, that's just the only date sort option we offer to the user.

**Comment by cbeer** [comment]
Decision from planning: offer both `Sort by Date (old to new)` and `Sort by Date (new to old)`, unless it becomes hairy to implement.

**Comment by corylown** [comment]
@jacobthill here's a summary of my current understanding of how we'd like date sort to behave. I'd like confirmation from you that this matches your expectations before proceeding with implementation. If this all seems right, I'll spin out some additional tickets because there are multiple moving parts and the order they are completed is important.

## Acceptance Criteria

- [ ] Ability to sort results by date in ascending order: `Sort by Date (old to new)`. **Ascending order sort uses the minimum date value** derived from `cho_date_range_norm_isim` for sorting.
- [ ] Ability to sort results by date in descending order: `Sort by Date (new to old)`. **Descending order uses the maximum date value** derived from `cho_date_range_norm_isim` for sorting.
- [ ] The UI includes an explanatory alert as described in #1470 when the sort by date feature is used.

## Tasks (will spin off and link to new issues to capture each)

- [ ] Modify the Solr schema to set the `sortMissingLast=true` attribute on the field types used to store dates for sorting (fields specified in the next tasks). Apply this schema change to dev Solr instance. (Need to determine how to do this.)
- [ ] Populate a new field in the Solr index that is single-valued, type `TrieIntField`, with dynamic field suffix of `_isi` and contains the **minimum** value from `cho_date_range_norm_isim`. Suggested field name: `cho_date_norm_min_isim`
- [ ] Populate a new field in the Solr index that is single-valued, type `TrieIntField`, with dynamic field suffix of `_isi` and contains the **maximum** value from `cho_date_range_norm_isim`. Suggested field name: `cho_date_norm_max_isim`
- [ ] Because of the Schema change (addition of `sortMissingLast=true` attribute) it is best practice to reindex all content in Solr.
- [ ] Configure the date sort options in the DLME app as specified above.
- [ ] Modify the DLME app UI to include an explanatory alert as described in #1470 when the sort by date feature is used.

**Comment by jacobthill** [comment]
@corylown yes that sounds right to me.
