### ISSUE TITLE
Language translation maps todo work

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/dlme#268]
Discussed on 8/31. @aaron-collier opened #235 about a concern of the presence of `eng` in the language facet. This does not absolutely need to be done before the end of the current work cycle.

* [x] Analysis of language data in existing data sources. We want to see where there are codes vs. literal values.
* [x] Identify the source of those codes (e.g. ISO 639-2 bibliographic, likely in MODS/MARC)
* [ ] Review the language translation maps and discuss a strategy for implementation (fuzzy matching, multiple translation maps).

**Comment by cmh2166** [comment]
First run-through:

- Stanford MODS: 
  - Geo-MODS, `language/languageTerm[@authority="iso639-2b"]`: eng
  - Other MODS, `language/languageTerm[@authority="iso639-2b"][@type="code"]`: eng
  - Other MODS, `language/languageTerm[@authority="iso639-2b"][@type="text"]`: English
- Princeton MODS:
  - Movie Posters MODS, `language/languageTerm[@type="code"][@authority="iso639-2b"]`: ara
- Harvard FGDC: n/a (no language fields)
- Penn TEI: 
  - `teiHeader/fileDesc/sourceDesc/msDesc/msContents/textLang`: Arabic [free text]
  - `teiHeader/fileDesc/sourceDesc/msDesc/msContents/textLang/@mainLang`: ara
  - `teiHeader/fileDesc/sourceDesc/msDesc/msContents/textLang/@otherLangs`: ara || hin san
- Penn MARC:
  - `008[35-37]`: abk (traject language_map in play here)
- ANS Local CSV: n/a (no language fields)
- Yale Local CSV: 
  - `Language`: Arabic |Greek, Ancient (to 1453) [MARC List for Languages Labels]
- Met Local CSV: n/a (no language fields)
- Penn Museum Local CSV (Near Eastern & Egyptian): n/a (no language fields)

**Comment by cmh2166** [comment]
Aimed for output: iso639-2b Labels (not codes)

MODS:
  - if `language/languageTerm[@authority="iso639-2b"][@type="text"]` use that
  - else if `language/languageTerm[@authority="iso639-2b"][@type="code"]` map to labels & use that without through-put
  - else if `language/languageTerm` (no type/authority indications) map presumed free text to labels as best possible & use that with through-put
  - ensure XPath doesn't care about order of attributes given

FGDC: n/a (no language fields)

TEI:
  - if `teiHeader/fileDesc/sourceDesc/msDesc/msContents/textLang/@mainLang` check it is a code, and map to label & use without through-put
  - AND if `teiHeader/fileDesc/sourceDesc/msDesc/msContents/textLang/@otherLangs` check it is a code, split based off of ' ' (single space) as a delimiter, and map to label & use without through-put
  - else is `teiHeader/fileDesc/sourceDesc/msDesc/msContents/textLang` map presumed free text to labels as best possible & use that with through-put

Penn MARC:
  - 008[35-37]: abk (traject language_map in play here, maps code to language label)

ANS Local CSV: n/a (no language fields)

Yale Local CSV:
  - If `Language`: split based off of '|' as a delimiter, use as label as found (close enough to iso639-2b)

Met Local CSV: n/a (no language fields)

Penn Museum Local CSV (Near Eastern & Egyptian): n/a (no language fields)

Work needed:

- [ ] rewrite existing language look-ups to follow logic above
- [ ] add iso639-2b code to iso639-2b labels lookup (overlaps significantly with but not entirely with Traject's current language translationMap)
- [ ] add free text to iso639-2b lookup

**Comment by cmh2166** [comment]
- Separate into new tickets for possible backlog: free text to iso639-2b (fuzzy matching included in this)
- iso639-2b codes && MARC language codes (overlap but not the same) to iso639-2b labels translation map (right now, just using the marc languages lookup we get for free with traject)
