### ISSUE TITLE
Set up new layout for metadata/config repositories

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/dlme#322]
Following the [analysis document](https://docs.google.com/document/d/1S9p8hYrV3OwkrUdWUCqlxWLMeuBrs_-6AL8yfMFtih8/edit) prepared by me, @jacobthill, @cmharlow, and @mejackreed, we need to set up the new layout for the repository/ies to hold the metadata and mappings. This relates directly to the work specified in #329 as well.

~We also need to discuss whether we're creating a new or separate Github organization for the repositories.~

- [x] sul-dlss/dlme-metadata#28: Move harvesting scripts to a new repository
- [x] remove harvesting scripts from dlme-metadata
- [x] create new repo (https://github.com/sul-dlss/dlme-harvest)
- [x] add capistrano and rubygems and a gemfile to the dlme-harvest repo
- [x] add readme on how to deploy and create capistrano config 
- [x] sul-dlss/dlme-metadata#35 have ops setup the new VM (with python, ruby, git, etc.)
- [ ] include documentation on how to run harvests on VM to readme
- [ ] test scripts with version of python
- [ ] setup git repo for dlme-metadata on VM and test pushing

* [x] Determine whether we need to move analysis scripts to a new repository
* [x] #377: Move Traject mappings, configurations, and macros to a new repository
