### ISSUE TITLE
Put our new environment into production

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/dlme#436]
* [x] Make a decision about how we want to handle cutover
    * We can handle downtime
     * Plan to complete transition on Monday, April 8
* [x] Redirect from staging.dlme.clir.org -> spotlight.stage.dlme.org
* [x] Ensure Terraform is ready for prod
* [x] Document how to deploy #500 
* [x] Add monitoring to comply with SLA #318 
* [x] Ensure existing database is migrated
* [x] Ensure @jacobthill can run end-to-end transform in stage, index in stage, and index in prod
* [x] Configure sending email #491 
* [x] Rerun existing production data providers in stage to prod using updated configs sul-dlss/dlme-metadata#16
* [x] @anarchivist, @waynegraham and Elizabeth to do a quick walk through to make sure the new prod site looks OK
* [x] Coordinate with @waynegraham for cutover
* [x] Redirect from spotlight.dlme.clir.org -> spotlight.dlmenetwork.org
* [x] Decommission old AWS infrastructure and give Wayne and DLSS Ops (inc. Julian) a heads up that we are doing that
  * [x] After signoff from Wayne/Mark/Elizabeth, stop servers in old DLME AWS account 
  * [x] Disable honeybadger for old prod site
  * [x] Close old AWS account

**Comment by anarchivist** [comment]
* [ ] Ensure terraform is ready for prod
* [ ] Ensure @jacobthill can run end-to-end transform in stage, index in stage, and index in prod
