### ISSUE TITLE
Implement right-to-left interface

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme#544]
Need a full right-to-left interface for Arabic language. Site should be bi-lingual [see notes](https://docs.google.com/document/d/1WpAtxAoFIADOYNkOwJ07vLOTflH8OCXJhAnLgQdJ7NY/edit). Metadata will come in many languages and need to display whatever is available in the 'record only' and 'browse record' views for Arabic and English. 

Edited below by @ggeisler on 10/30/2019 to make this an epic with actionable subtasks:

- [x] #606 Enable Arabic locale in DLME exhibit
- [x] #601 Add Arabic translations for all non-metadata UI elements
- [x] #609 When site locale is Arabic, change UI to RTL
- [x] #608 Display site-wide elements as RTL
- [x] #655 Use an Arabic font when the locale is Arabic
- [x] #673 Display breadcrumbs as RTL
- [x] #674 Display facets as RTL
- [x] #676 Display search results as RTL

11/12/2019: Will hold off on mockups for the additional pages below since with the addition of a Bootstrap RTL library we hope most of the details will be handled automatically. But we can use the todo items to indicate when these pages have been successfully RTLed:

- [ ] Display browse categories page as RTL
- [ ] Display browse detail page as RTL
- [ ] Display home page content as RTL
- [ ] Display about pages as RTL
- [ ] Display Statistics page as RTL
- [ ] Display feedback form as RTL
- [ ] Display footer as RTL

- [ ] Figure out an approach for sharing these customizations upstream

**Comment by jacobthill** [comment]
@anarchivist @ggeisler I have tried to separate this ticket so that it involves only one repo. It may need to be broken down to smaller tickets. @ggeisler let me know how you want to proceed
