### ISSUE TITLE
Add Arabic translations for all non-metadata UI elements

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/dlme#601]
We have another high-level internationalization ticket already, but I think it would be helpful to have a concise list of the specific tickets that need to be completed in order for us to say we can display the site in Arabic. 

Arabic metadata is not included here, since that involves very different tasks and is covered by existing tickets. 

The first few would be good to get done soon so we can switch the exhibit language to Arabic and validate that Arabic-translated UI labels and exhibit-specific labels and text content is used for the Arabic version of the exhibit:

- [x] [Spotlight#2214](https://github.com/projectblacklight/spotlight/pull/2214) Add Arabic locale file to Spotlight
- [x] Update DLME to use Spotlight release with Arabic locale file
- [ ] Provide Arabic translations for exhibit-specific labels and text (via the exhibit Curation > Translations UI)
- [ ] Provider Arabic translations for Blacklight  demo labels and text (https://github.com/projectblacklight/demo.projectblacklight.org/blob/master/config/locales/en.yml)
- [ ] Translate [DLME application](https://github.com/sul-dlss/dlme/issues/828) specific strings 

The tasks below are necessary eventually to show the complete UI in Arabic, but aren't blockers to other work so aren't as time-sensitive:

- [x] [#586](https://github.com/sul-dlss/dlme/issues/586) Add Arabic locale file to Blacklight (https://github.com/projectblacklight/blacklight/pull/2190)
	- [x] [projectblacklight/blacklight#2197](https://github.com/projectblacklight/blacklight/issues/2197) Add Arabic pluralizations
- [x] [#591](https://github.com/sul-dlss/dlme/issues/591) Add Arabic locale file to Blacklight-gallery (needs review: https://github.com/projectblacklight/blacklight-gallery/pull/59)
- [x] Update DLME to use releases of Blacklight and Blacklight-gallery that include the Arabic locale files
