### ISSUE TITLE
Finalize curated page content and UI-based configuration

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/dlme#960]
This is a story ticket to keep track of the curator UI based tasks we (mostly some combination of @jacobthill and I) need to complete before DLME launch. I don't expect any of the tickets I'm including here to require development effort.

- [x] #961 - Update facets labels, visibility, and order
- [x] #962 - Update metadata field labels, visibility, and order
- [x] #963 - Add final homepage content
- [x] #964 - Finalize browse categories
- [x] #965 - Finalize About page content, ordering, and verify form submission works
